version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - gcr

registries:
  gcr:
    type: "docker-registry"
    url: "https://gcr.io"
    username: "${{ secrets.GCR_USERNAME }}"
    password: "${{ secrets.GCR_PASSWORD }}"
